### ISSUE TITLE
multiple tag size

### ISSUE THREAD

**Issue by mkinnaman** [mcmero/SVclone#12]
HI!

Got thrown this error tonight:

`ValueError: multiple tag sizes in /work/isabl/data/analyses/65/57/166557/I-H-136433-T5-1-D1-1.bam: [151, 151, 151, 73, 151, 151, 151, 151, 151, 151]`

Is there anyway to bypass this? Does the BAM need to be realigned?

Thanks!

**Comment by mcmero** [comment]
This error is due to different read sizes in your bam file, which may be due to read trimming, for example. SVclone works under the assumption that reads are consistent sizes, so there may be unexpected effects due to different read sizes (we did not test the algorithm on samples with varying read sizes).

The easiest 'fix' would be to manually change the `read_len`, `insert_len` and `insert_std` parameters under `[BamParameters]` in your `svclone_config.ini` file. You could use an average read length here. This will bypass the size check.

Ultimately, the best option will be based on the QC metrics of your sequencing data. If your variation in read size is due to trimming, you could try untrimmed input if the adapter contamination level is low, or trim to a consistent read length. Another option is to remove small read length, depending on your read distribution.

**Comment by mkinnaman** [comment]
Thanks for your reply. I had been running with those specified but for some reason it didn't recognize it. I reran it on an older set up I had of SVClone and it worked. Will close out.
