### ISSUE TITLE
All SNVs getting filtered 

### ISSUE THREAD

**Issue by willhooper** [mcmero/SVclone#13]
Hi, 

When attaching CNV and SNVs in the filter step, all of my SNVs get filtered out by the following step: 
`Filtered out XX SNVs with missing or invalid copy-numbers`

I'm guessing that this is a VCF formatting issue, as the same issue does not happen when directly using mutect output. What VCF field(s) is this filter using to mark variants for exclusion? 

THanks,
Will

**Comment by mcmero** [comment]
This will most likely be due to some kind of mismatch between the copy-number and SNV input files. Check whether your chromosome names are the same between your SNV and CNV files (e.g. one might have chr and the other without). Which VCF format are you using other than mutect's output? The only fields for SNVs that should be used in matching copy-numbers should be chromosome and position. If you can provide a short sample of the SNV and CNV files that would help.

**Comment by willhooper** [comment]
> This will most likely be due to some kind of mismatch between the copy-number and SNV input files.
That's exactly what the issue was -- I didn't realize ascat was stripping the 'chr' prefix. I'm not sure why the raw mutect output was working at all... 

Thanks!
