### ISSUE TITLE
Warning: record contains invalid attributes, skipping

### ISSUE THREAD

**Issue by Biojenifer** [mcmero/SVclone#16]
Hi!

I was wondering why is this warning happening? This occurs in the `count` step, with a lot of reads, so after 8 hours running I get no results and `sample_svinfo.txt` file is empty. I am not sure if it is a problem with the bam file or if there are some inconsistencies between the bam's data and the input file information. 

The SV that I am analyzing are mobile element insertions and the annotate step classifies them incorrectly sometimes (for example: as inversions). I also tryed to specify myself the type of variant (I classified them as DUP first and as INTRX in another run), but the problem occurs anyway. So I am not sure if maybe the missclasification of this kind of variants can be causing the problem. If that is the case, which is the best way to indicate a mobile element insertion? I only see this options of classification: 

inversion_class: INV
deletion_class: DEL
dna_gain_class: DUP,INTDUP
dna_loss_class: DEL,INV,TRX
itrx_class: INTRX

How can I solve this?
Thanks!

**Comment by mcmero** [comment]
Regarding invalid attributes, this is likely due to the formatting of the bam file's attributes. Would you be able to post a few records from the bam file? If so, I might be able to narrow down the problem.

Regarding mobile element insertions, these should be classified as TRX, or possibly INTRX + DEL if it's inter-chromosomal. As far as SVclone works, it doesn't really matter as only events in the `dna_gain_class` are VAF adjusted, all others are treated the same. The classification is a bit rudimentary, so it might make some mistakes sometimes, especially if SVclone is configured to infer directionality (using the SV caller's directions is recommended). The classification info is used further downstream, so that shouldn't be causing problems with the read counting step.

**Comment by Biojenifer** [comment]
Thanks for your answer! I finally think that the problem was caused by another warning, which was discussed here: [](https://github.com/mcmero/SVclone/issues/7). I tryed to manually fill insert size field and the problem has been solved.
