### ISSUE TITLE
AttributeError when combining ccube_sv_input files

### ISSUE THREAD

**Issue by mdiaz09** [mcmero/SVclone#27]
Similar to #10 I am interested in analyzing paired samples but am having trouble running the clustering function with the combined input. I combined the two ccube_sv_input files and averaged the refcounts. I encountered the following error when running SVclone cluster  `AttributeError: 'DataFrame' object has no attribute 'gtype1' ` Is this error due to missing or malformed inputs?

Thank you in advance,

Mike

**Comment by mdiaz09** [comment]
I misunderstood the conversation in #10, ccube_sv_input is used as an input for pyclone, not ccube. The filtered_svs.tsv dataset is the input for ccube

**Comment by mcmero** [comment]
Just to clarify, the filtered_svs.tsv file is used as input to SVclone's cluster step, and is converted to a ccube_sv_input.txt file as input for ccube clustering (this is an internal step and occurs due to legacy reasons). In #10, the user asked about converting this input file into PyClone input, as SVclone does not support paired-sample clustering.
